require 'active_support/all'
require 'money'

require 'structural/version'
require 'structural/missing_attribute_error'
require 'structural/hashifier'
require 'structural/model/definer'
require 'structural/model/descriptor'
require 'structural/model/type_casts'
require 'structural/model/field'
require 'structural/model/association'
require 'structural/model/has_one'
require 'structural/model/has_many'
require 'structural/model'
require 'structural/timestamps'
